apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: mai-website-dev-deployment
  labels:
    app: mai-website-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mai-website-dev
  template:
    metadata:
      labels:
        app: mai-website-dev
    spec:
      hostname: mai-website-dev
      containers:
        - name: mai-website-dev
          image: 408153089286.dkr.ecr.ap-south-1.amazonaws.com/mai-website-dev:<VERSION>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '1024Mi'
              cpu: '500m'
            limits:
              memory: '2048Mi'
              cpu: '750m'
          # readinessProbe:
          #     httpGet:
          #       path: /health
          #       port: 3000
          #     initialDelaySeconds: 60
          #     timeoutSeconds: 10
          # livenessProbe:
          #     httpGet:
          #       path: /health
          #       port: 3000
          #     initialDelaySeconds: 60
          #     periodSeconds: 5
          #     timeoutSeconds: 10
          #     failureThreshold: 4                                             
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # env:
            # - name: PORT
            #   valueFrom:
            #     secretKeyRef:
            #       key: PORT
            #       name: dev-mai-website          
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mai-website-dev-svc
  labels:
    svc: mai-website-dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: mai-website-dev
